apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: master
    tier: backend
  name: redis-master
spec:
  containers:
  - image: redis
    name: redis-master
    ports:
    - containerPort: 6379
    resources:
      requests:
        cpu: 300m
        memory: 1000Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: master
    tier: backend
  name: redis-master
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
status:
  loadBalancer: {}
