apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  labels:
    app: websocket
    role: server
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8001
      nodePort: 30000
  selector:
    app: websocket-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
spec:
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        env:
          - name: GET_HOSTS_FROM
            value: dns
        image: websocket-server:1.0
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          periodSeconds: 1
        ports:
        - containerPort: 80
